import timeit
import sys
import textwrap

####
N = 100_000_000
opt_g = len(sys.argv) == 2 and sys.argv[1] == "global"

if opt_g:
    def bench_global():
        global count, i
        count = 0
        for _ in range(N):
            count += 1
        return count
    source = "bench_global()"
    caption_global = "in function(with global var) scope"
else:
    source = textwrap.dedent(f"""\
        count = 0
        for _ in range({N}):
            count += 1
        """)
    caption_global = "in top-level scope"

code = compile(source, "<string>", "exec")

print(f'## benchmarking looping "add 1" {N} times')
bt = timeit.default_timer()
exec(code)
print(f"{caption_global}: elapsed time: {timeit.default_timer()-bt}")

def bench_local() -> int:
    count = 0
    for _ in range(100_000_000):
        count += 1
    return count

bt = timeit.default_timer()
bench_local()
print(f"in function scope: elapsed time: {timeit.default_timer()-bt}")

#####################
import dis
import io
import difflib
from rich.console import Console
from rich.syntax import Syntax

print("## diff in discompile both code")

def cut_line_heading(lines, n_cut = 3):
    return (line[n_cut:] for line in lines)

def get_dis_text(func):
    """helper function to retrieve a string generated by dis"""
    buf = io.StringIO()
    dis.dis(func, file=buf)
    cut_lines = cut_line_heading(buf.getvalue().splitlines())
    return "\n".join(cut_lines)

if opt_g:
    global_dis = get_dis_text(bench_global)
else:
    global_dis = get_dis_text(code)

bench_local_dis = get_dis_text(bench_local)

diff_txt = "\n".join(difflib.unified_diff(global_dis.splitlines(), bench_local_dis.splitlines(),
                            fromfile=caption_global, tofile="in function scope"))
syntax = Syntax(diff_txt, "diff", theme="monokai")

console = Console()
console.print(syntax)